sudo: required
dist: xenial

notifications:
  email:
    recipients:
      - kaushikrohit325@gmail.com
      - prasad.talasila@eng.au.dk
    on_success: change
    on_failure: always

script:
- bash tests/test_runner.sh
